#! /usr/bin/env python
import sys
import os
import filecmp
from shutil import copyfile

# path to the configuration file
update_conf = 'conf.pykeep'

def update(src_dst, init, back, L):
    if init:
        for mv in src_dst:
            (src, dst) = mv
            if (not os.path.isfile(src)) \
              or (not filecmp.cmp(src, dst) and src in L):
                copyfile(dst, src)
                print('Imported : ' + src + ' from ' + dst)
    else:
        if back:
            for mv in src_dst:
                (src, dst) = mv
                if os.path.isfile(dst + '_old') and src in L:
                    if os.access(dst, os.W_OK):
                        copyfile(dst + '_old', dst + '_tmp')
                        copyfile(dst, dst + '_old')
                        copyfile(dst + '_tmp', dst)
                        os.remove(dst + '_tmp')
                        print('Backed : ' + dst)
                    else:
                        print('Permission Denied to replace ' + dst + ' with '\
                              + dst + '_old' + '\nTry using root')
        else:
            for mv in src_dst:
                (src, dst) = mv
                if not filecmp.cmp(src, dst):
                    if os.access(dst, os.W_OK):
                        copyfile(dst, dst + '_old')
                        copyfile(src, dst)
                        print('Updated : ' + src)
                    else:
                        print('Permission Denied to replace ' + dst + ' with '\
                               + src + "\nTry using root")

def read_line(line):
    src, dst = '', ''
    test, start = False, False 
    b1, b2 = 0, 0
    for char in line:
	if char == chr(34) or char == chr(39):
            if b1 < 2:
                b1 += 1
            elif test:
                b2 +=1
                if b2 == 2:
                    break
        if b1 == 1:
            if start:
                src += char
            else: 
                start = True
        else:
            if b1 == 2 and char == '>':
                test = True
                start = False
            elif b2 == 1:
                if start:
                    dst += char
                else: 
                    start = True
    return src, dst

def read_conf(init, back, L):
    conf = open(update_conf, 'r')
    src_dst = []
    for line in conf:
        for char in line:
            if char == '#':
                break
            if char != ' ':
                (src, dst) = read_line(line)
                #dst = home + dst
                #print(dst)
                if (os.path.isfile(src) and os.path.isfile(dst)) \
                  or (init and os.path.isfile(dst)): 
                    src_dst.append((src, dst))
                break
    update(src_dst, init, back, L)

def create_config_file():
    conffile = open('conf.pykeep', 'w+')
    conffile.write("#==============================#\n"
                   "# -- # Pykeep config file # -- #\n"
                   "#==============================#\n \n"
                   "# exemple line :\n"
                   "# 'i3config' > '../.config/i3/config'")
    conffile.close()

def argv_list(l):
    L = []
    for i in range(2, l):
        L.append(sys.argv[i])
    return L

if __name__ == '__main__':
    l = len(sys.argv)
    if  l >= 2 and sys.argv[1] == '-i':
        read_conf(True, False, argv_list(l))
    else:
        if l >= 2 and sys.argv[1] == '-b':
            if l > 2:
                read_conf(False, True, argv_list(l))
        else:
            if l == 1:
                if not os.path.isfile(update_conf):
                    print("Can't find the configuration file use -f to create"
                          ' one or verify the path to your file')
                else:
                    read_conf(False, False, [])
            else:
                if sys.argv[1] == '-f':
                    yn = 'y'
                    if os.path.isfile('conf.pykeep'):
                        yn = raw_input('You already have a'
                                       'configuration file\n'
                                       'Would you like to replace it ? y/n : ')
                    if yn == 'y':
                        create_config_file()
                        print("Created a config file 'conf.pykeep'")
                else:
                    if sys.argv[1] == '-h':
                        print('See https://github.com/Dirtyhenki/pykeep')
                    else:
                        print('Unknown argument : ' + sys.argv[1])
