#! /usr/bin/env python
import sys
import os.path
import filecmp
from shutil import copyfile

# path to the configuration file
update_conf = "conf.pykeep"
init = False

def update(src_dst):
    if init:
        for mv in src_dst:
            (src, dst) = mv
            copyfile(dst, src)
            print("Imported : " + src + " from " + dst)
    else:
        for mv in src_dst:
            (src, dst) = mv
            if not filecmp.cmp(src, dst):
                copyfile(dst,dst+"_old")
                copyfile(src, dst)
                print("Updated : " + src)

def read_line(line):
    src, dst = "", ""
    test, start = False, False 
    b1, b2 = 0, 0
    for char in line:
	if char == chr(34) or char == chr(44):
            if b1 < 2:
                b1 += 1
            elif test:
                b2 +=1
                if b2 == 2:
                    break
        if b1 == 1:
            if start:
                src += char
            else: 
                start = True
        else:
            if b1 == 2 and char == ">":
                test = True
                start = False
            elif b2 == 1:
                if start:
                    dst += char
                else: 
                    start = True
    return src, dst

def read_conf(i):
    if not os.path.isfile(update_conf):
        return
    if i == True :
        global init
        init = True
    conf = open(update_conf, "r")
    src_dst = []
    for line in conf:
        for char in line:
            if char == "#":
                break
            if char != " ":
                (s, d) = read_line(line)
                if (os.path.isfile(s) and os.path.isfile(d)) or (init and os.path.isfile(d)): 
                    src_dst.append((s, d))
                break
    update(src_dst)

def create_config_file():
    conffile = open("conf.pykeep","w+")
    conffile.write("#==============================#\n# -- # Pykeep config file # -- #\n#==============================#\n\n# exemple line :\n# 'i3config' > '../.config/i3/config'")
    conffile.close()

if __name__ == "__main__":
    l = len(sys.argv)
    if l > 2:
        print("too many arguments")
    else:
        if l == 1:
            if not os.path.isfile(update_conf):
                print("Can't find the configuration file use -f to create one or verify the path to your file")
            else:
                read_conf(False)
        else:
            if sys.argv[1] == "-f":
                create_config_file()
                print("created a config file 'conf.pykeep'")
            else:
                if sys.argv[1] == "-h":
                    print("See https://github.com/Dirtyhenki/pykeep")
                else:
                    if sys.argv[1] == "-i":
                        read_conf(True)
                    else:
                        print("unknown argument")
